In [19]:
import pandas as pd
url = "https://it.wikipedia.org/wiki/Prefissi_telefonici_italiani"
df = pd.read_html(url)[0]
print(type(df.columns))
print(df.columns)
converters = {c:lambda c: str(c) for c in df.columns}
# print(converters)
# converters = {i:str for i in range(len(df.columns))}
print(converters)
print(len(df.columns))
df = pd.read_html(url, converters=converters)[0]


df.to_excel("prefissi_italiani.xlsx", index=False)
df

<class 'pandas.core.indexes.base.Index'>
Index(['Prefisso[3]', 'Compartimento', 'Distretto', 'Altre città[4]',
       'Aree locali', 'Provincia'],
      dtype='object')
{'Prefisso[3]': <function <dictcomp>.<lambda> at 0x000001A955BB1E40>, 'Compartimento': <function <dictcomp>.<lambda> at 0x000001A957E665C0>, 'Distretto': <function <dictcomp>.<lambda> at 0x000001A957E66520>, 'Altre città[4]': <function <dictcomp>.<lambda> at 0x000001A957E659E0>, 'Aree locali': <function <dictcomp>.<lambda> at 0x000001A957E64360>, 'Provincia': <function <dictcomp>.<lambda> at 0x000001A957E66840>}
6

,Prefisso[3],Compartimento,Distretto,Altre città[4],Aree locali,Provincia
0,004191,Lugano (Svizzera),Campione d'Italia (CO),NaN,Campione d'Italia,CO
1,010,Genova,Genova,NaN,"Arenzano, Busalla, Genova","GE, AL"
2,011,Torino,Torino,"Moncalieri (TO), Rivoli (TO)","Avigliana, Carmagnola, Caselle Torinese, Chier...","TO, AT, CN"
3,0121,Torino,Pinerolo (TO),NaN,Pinerolo,TO
4,0122,Torino,Susa (TO),NaN,Susa,TO
...,...,...,...,...,...,...
228,0982,Catanzaro,Paola (CS),NaN,Paola,CS
229,0983,Catanzaro,Rossano (CS),NaN,"Cariati, Corigliano Calabro, Rossano",CS
230,0984,Catanzaro,Cosenza,NaN,"Bisignano, Cosenza, San Giovanni in Fiore, San...","CS, KR"
231,0985,Catanzaro,Scalea (CS),NaN,Scalea,CS
232,099,Bari,Taranto,NaN,"Fragagnano, Ginosa, Grottaglie, Manduria, Mass...",TA