In [4]:
import pandas as pd
url = "https://it.wikipedia.org/wiki/Prefissi_telefonici_italiani"
df1 = pd.read_html(url)
df = df1[0]
print(type(df.columns))
print(df.columns)
converters = {c:lambda c: str(c) for c in df.columns}
# print(converters)
# converters = {i:str for i in range(len(df.columns))}
print(converters)
print(len(df.columns))
df = pd.read_html(url, converters=converters)[0]


df.to_excel("prefissi_italiani.xlsx", index=False)
df

<class 'pandas.core.indexes.base.Index'>
Index(['Prefisso[4]', 'Compartimento', 'Distretto', 'Altre città[5]',
       'Aree locali', 'Provincia'],
      dtype='object')
{'Prefisso[4]': <function <lambda> at 0x79bcd55294e0>, 'Compartimento': <function <lambda> at 0x79bcd55293a0>, 'Distretto': <function <lambda> at 0x79bcd5529440>, 'Altre città[5]': <function <lambda> at 0x79bcd5529080>, 'Aree locali': <function <lambda> at 0x79bcd5528fe0>, 'Provincia': <function <lambda> at 0x79bcd5529760>}
6

,Prefisso[4],Compartimento,Distretto,Altre città[5],Aree locali,Provincia
0,004191,Lugano (Svizzera),Campione d'Italia (CO),NaN,Campione d'Italia,CO
1,010,Genova,Genova,NaN,"Arenzano, Busalla, Genova","GE, AL"
2,011,Torino,Torino,"Moncalieri (TO), Rivoli (TO)","Avigliana, Carmagnola, Caselle Torinese, Chier...","TO, AT, CN"
3,0121,Torino,Pinerolo (TO),NaN,Pinerolo,TO
4,0122,Torino,Susa (TO),NaN,Susa,TO
...,...,...,...,...,...,...
228,0982,Catanzaro,Paola (CS),NaN,Paola,CS
229,0983,Catanzaro,Rossano (CS),NaN,"Cariati, Corigliano Calabro, Rossano",CS
230,0984,Catanzaro,Cosenza,NaN,"Bisignano, Cosenza, San Giovanni in Fiore, San...","CS, KR"
231,0985,Catanzaro,Scalea (CS),NaN,Scalea,CS
232,099,Bari,Taranto,NaN,"Fragagnano, Ginosa, Grottaglie, Manduria, Mass...",TA

In [8]:
len(df1)
df1[1]
df1

[     Prefisso[4]      Compartimento               Distretto  \
 0           4191  Lugano (Svizzera)  Campione d'Italia (CO)
 1             10             Genova                  Genova
 2             11             Torino                  Torino
 3            121             Torino           Pinerolo (TO)
 4            122             Torino               Susa (TO)
 ..           ...                ...                     ...
 228          982          Catanzaro              Paola (CS)
 229          983          Catanzaro            Rossano (CS)
 230          984          Catanzaro                 Cosenza
 231          985          Catanzaro             Scalea (CS)
 232           99               Bari                 Taranto

                    Altre città[5]  \
 0                             NaN
 1                             NaN
 2    Moncalieri (TO), Rivoli (TO)
 3                             NaN
 4                             NaN
 ..                            ...
 228                           NaN
 229                           NaN
 230                           NaN
 231                           NaN
 232                           NaN

                                            Aree locali   Provincia
 0                                    Campione d'Italia          CO
 1                            Arenzano, Busalla, Genova      GE, AL
 2    Avigliana, Carmagnola, Caselle Torinese, Chier...  TO, AT, CN
 3                                             Pinerolo          TO
 4                                                 Susa          TO
 ..                                                 ...         ...
 228                                              Paola          CS
 229               Cariati, Corigliano Calabro, Rossano          CS
 230  Bisignano, Cosenza, San Giovanni in Fiore, San...      CS, KR
 231                                             Scalea          CS
 232  Fragagnano, Ginosa, Grottaglie, Manduria, Mass...          TA

 [233 rows x 6 columns],
      #  Prefisso                                           Province  \
 0    1         6          Roma, Latina, Viterbo, Città del Vaticano
 1    2        81                 Napoli, Caserta, Avellino, Salerno
 2    3         2  Milano, Varese, Lodi, Como, Bergamo, Monza e B...
 3    4        11                                Torino, Cuneo, Asti
 4    5        80     Bari, Barletta-Andria-Trani, Brindisi, Taranto
 5    6        91                                            Palermo
 6    7        95                         Catania, Siracusa, Messina
 7    8        30                                            Brescia
 8    9        55                             Firenze, Arezzo, Prato
 9   10        51                                   Bologna, Ferrara
 10  11        35                                   Bergamo, Brescia
 11  12        49                                    Padova, Venezia
 12  13        45                                             Verona
 13  14        10                                Genova, Alessandria

    Popolazione                                 Quantità di comuni
 0    3 900 555  72: 66 (Roma), 4 (Latina), 1 (Viterbo) e Città...
 1    3 678 198  138: 92 (Napoli), 20 (Caserta), 12 (Avellino) ...
 2    3 025 008  141: 114 (Milano), 6 (Varese), 8 (Lodi), 4 (Co...
 3    1 933 665            145: 136 (Torino), 3 (Cuneo) e 6 (Asti)
 4    1 363 418  45: 41 (Bari), 1 (Barletta-Andria-Trani), 2 (B...
 5    1 156 779                                   59: 59 (Palermo)
 6    1 051 678       54: 48 (Catania), 3 (Siracusa) e 3 (Messina)
 7    1 005 018                                 124: 124 (Brescia)
 8      920 562           43: 33 (Firenze), 8 (Arezzo) e 2 (Prato)
 9      881 882                     45: 44 (Bologna) e 1 (Ferrara)
 10     833 742                    158: 157 (Bergamo), 1 (Brescia)
 11     822 381                      74: 71 (Padova) e 3 (Venezia)
 12     791 393                                    77: 77 (Verona)
 13     712 978                  36: 34 (Genova) e 2 (Alessandria)  ]